// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SCADASMSSystem.Web.Data;

#nullable disable

namespace SCADASMSSystem.Web.Migrations
{
    [DbContext(typeof(SCADADbContext))]
    [Migration("20260421000000_RenameTablesWithScadaPrefix")]
    partial class RenameTablesWithScadaPrefix
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SCADASMSSystem.Web.Models.AlarmAction", b =>
                {
                    b.Property<int>("BlockId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BLOCK_INDEX");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlockId"));

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ACTIONS_ON_ACTIVE");

                    b.Property<string>("AlarmConditionName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ALARM_CONDITION_NAME");

                    b.Property<string>("AlarmDescription")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("DESCRIPTION");

                    b.Property<int?>("AlarmIdInt")
                        .HasColumnType("int")
                        .HasColumnName("ALARM_ID");

                    b.Property<int>("Deleted")
                        .HasColumnType("int")
                        .HasColumnName("DELETED");

                    b.HasKey("BlockId");

                    b.HasIndex("AlarmIdInt");

                    b.HasIndex("Deleted");

                    b.ToTable("AlarmConditions");
                });

            modelBuilder.Entity("SCADASMSSystem.Web.Models.AlarmActionAudit", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("audit_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("action_type");

                    b.Property<int>("BlockId")
                        .HasColumnType("int")
                        .HasColumnName("block_index");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("ip_address");

                    b.Property<DateTime>("ModifiedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("modified_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("modified_by");

                    b.Property<string>("NewAction")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("new_action");

                    b.Property<int?>("NewGroupId")
                        .HasColumnType("int")
                        .HasColumnName("new_group_id");

                    b.Property<string>("OldAction")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("old_action");

                    b.Property<int?>("OldGroupId")
                        .HasColumnType("int")
                        .HasColumnName("old_group_id");

                    b.HasKey("AuditId");

                    b.HasIndex("ActionType");

                    b.HasIndex("BlockId");

                    b.HasIndex("ModifiedAt");

                    b.ToTable("scada_alarm_action_audit");
                });

            modelBuilder.Entity("SCADASMSSystem.Web.Models.DBListBlock", b =>
                {
                    b.Property<int>("BlockIndex")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("BLOCK_INDEX");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlockIndex"));

                    b.Property<string>("BlockName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("BLOCK_NAME");

                    b.HasKey("BlockIndex");

                    b.HasIndex("BlockName");

                    b.ToTable("DBLIST");
                });

            modelBuilder.Entity("SCADASMSSystem.Web.Models.DateDimension", b =>
                {
                    b.Property<int>("DateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("date_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DateId"));

                    b.Property<string>("DayName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("day_name");

                    b.Property<byte>("DayOfMonth")
                        .HasColumnType("tinyint")
                        .HasColumnName("day_of_month");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint")
                        .HasColumnName("day_of_week");

                    b.Property<short>("DayOfYear")
                        .HasColumnType("smallint")
                        .HasColumnName("day_of_year");

                    b.Property<DateTime>("FullDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("full_date");

                    b.Property<string>("HebrewDate")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("hebrew_date");

                    b.Property<bool>("IsJewishHoliday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_jewish_holiday");

                    b.Property<bool>("IsSabbaticalHoliday")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_sabbatical_holiday");

                    b.Property<bool>("IsWeekend")
                        .HasColumnType("bit")
                        .HasColumnName("is_weekend");

                    b.Property<string>("JewishHoliday")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("jewish_holiday");

                    b.Property<byte>("Month")
                        .HasColumnType("tinyint")
                        .HasColumnName("month");

                    b.Property<string>("MonthName")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("month_name");

                    b.Property<byte>("Quarter")
                        .HasColumnType("tinyint")
                        .HasColumnName("quarter");

                    b.Property<byte>("WeekOfYear")
                        .HasColumnType("tinyint")
                        .HasColumnName("week_of_year");

                    b.Property<short>("Year")
                        .HasColumnType("smallint")
                        .HasColumnName("year");

                    b.HasKey("DateId");

                    b.HasIndex("FullDate")
                        .IsUnique();

                    b.HasIndex("IsSabbaticalHoliday");

                    b.ToTable("scada_date_dimension");
                });

            modelBuilder.Entity("SCADASMSSystem.Web.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("group_name");

                    b.HasKey("GroupId");

                    b.ToTable("scada_groups");
                });

            modelBuilder.Entity("SCADASMSSystem.Web.Models.GroupMember", b =>
                {
                    b.Property<int>("GroupMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("group_member_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupMemberId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("GroupMemberId");

                    b.HasIndex("UserId");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique();

                    b.ToTable("scada_group_members");
                });

            modelBuilder.Entity("SCADASMSSystem.Web.Models.SmsAudit", b =>
                {
                    b.Property<int>("AuditId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("audit_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuditId"));

                    b.Property<string>("AlarmDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alarm_description");

                    b.Property<string>("AlarmId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("alarm_id");

                    b.Property<string>("ApiResponse")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("api_response");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int?>("GroupId")
                        .HasColumnType("int")
                        .HasColumnName("group_id");

                    b.Property<string>("MessageStatus")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("message_status");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("phone_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("AuditId");

                    b.HasIndex("AlarmId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("scada_sms_audit");
                });

            modelBuilder.Entity("SCADASMSSystem.Web.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("phone_number");

                    b.Property<bool>("SmsEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true)
                        .HasColumnName("sms_enabled");

                    b.Property<bool>("SpecialDaysEnabled")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("special_days_enabled");

                    b.Property<string>("TZ")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("tz");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("user_name");

                    b.HasKey("UserId");

                    b.HasIndex("PhoneNumber");

                    b.HasIndex("SmsEnabled");

                    b.HasIndex("SpecialDaysEnabled");

                    b.ToTable("scada_users");
                });

            modelBuilder.Entity("SCADASMSSystem.Web.Models.GroupMember", b =>
                {
                    b.HasOne("SCADASMSSystem.Web.Models.Group", "Group")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SCADASMSSystem.Web.Models.User", "User")
                        .WithMany("GroupMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SCADASMSSystem.Web.Models.SmsAudit", b =>
                {
                    b.HasOne("SCADASMSSystem.Web.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId");

                    b.HasOne("SCADASMSSystem.Web.Models.User", "User")
                        .WithMany("SmsAudits")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SCADASMSSystem.Web.Models.Group", b =>
                {
                    b.Navigation("GroupMembers");
                });

            modelBuilder.Entity("SCADASMSSystem.Web.Models.User", b =>
                {
                    b.Navigation("GroupMembers");

                    b.Navigation("SmsAudits");
                });
#pragma warning restore 612, 618
        }
    }
}
